### ISSUE TITLE
MAC resolution not working

### ISSUE THREAD

**Issue by jmhoya** [rorist/android-network-discovery#5]
Hi,
For some reason the vendor name for each MAC address is not displayed, all discovered hosts are labeled as "Unknown". I've tried the app on several devices and Android versions and they all have the same problem. The NIC database file is fine, I opened it on my computer and there was an entry for some of the devices in my network (I didn't check all of them).

Does anybody have any idea what could the problem be? Or at least which are the relevant classes and/or methods so I can take a look and try to figure it out.

Thanks to anyone who reads this. This project is great, by the way. There aren't any other free (as in freedom) network discovery apps for Android as far as I'm concerned, and it's a pity that it's receiving so little attention from the community :(

**Comment by akashqss** [comment]
I am getting  "Unknown" at place of all device's name. Please resolve this issue.

**Comment by rorist** [comment]
Hi, did you update the database from the General preferences ?

**Comment by akashqss** [comment]
I don't know how to update database from General preferences. Please guide me how to do this.

**Comment by akashqss** [comment]
Sorry for above comment. I have update database from General preferences. But result is same.

**Comment by rorist** [comment]
which version of the app do you have ? (you can see it in the Options)

**Comment by akashqss** [comment]
vesrion- 0.3.5

**Comment by akashqss** [comment]
Have you got solution?
